anabot/runtime/functions.py
The teres.bkr_handlers is used in the code, but the bkr_handlers needs to be
imported explicitely.
=> Fix missing teres import

anabot/runtime/installation/hub/partitioning/advanced/__init__.py
Both RHEL-8 and RHEL-9 have the icon named as "Warning", not "Warnings" which
was probably used in RHEL-7 installer.
=> Look for "Warning" icon in error bar

etc/systemd/system/anabot.service
Adding a delay between Anaconda and Anabot start should
bring a better level of certainty that Anaconda (service)
started fully (not just reportedly), including initialization
of AT-SPI D-Bus and connection to it.
With this change, Anabot should connect properly to the
existing accessibility D-Bus (via AT-SPI/dogtail) and find
the application, instead of creating its own bus instance
in parallel to the other one, which would lead to traceback
with gi.repository.GLib.GError: atspi_error or SearchError.
This is just a workaround to get rid of the momentary tracebacks,
ideally this should be solved properly on Anaconda side.
=> [RTT-2978] Add workaround for startup traceback

anabot/runtime/installation/hub/connect_to_redhat/registration.py
It may take quite a long time for the registration to complete,
which can cause unnecessary timeouts.
=> CDN: Increase timeout for Unregister button

anabot/runtime/installation/hub/software_selection.py
It can take quite a long time for group metadata download to
finish when CDN is used as installation source, which blocks
the software selection button for a long time, causing timeouts
with the default value (7 s).
The longest time for the button to become active I measured when experimenting with CDN registration was something less than 3 minutes. I guess 5 minutes should cover even the worst-case scenarios.
I also thought about implementing a special timeout only for CDN installation source, but in the end it seemed overcomplicated to me.
=> Increase timeout for software selection spoke button

anabot/runtime/installation/welcome/language.py
It seems that the whole Anaconda application is not focused at first
under some circumstances. This may cause that the language is not
entered properly in the search field and subsequently make Anabot crash
when it tries to click on a language cell that is out of the visible area.
This fix ensures that the language is found and therefore the
language cell is displayed in the visible area.
=> [RTT-4715] Ensure that language is entered properly

anabot/preprocessor/snippets/installation/hub/autopart.xml, anabot/runtime/installation/hub/partitioning/__init__.py, anabot/runtime/installation/hub/partitioning/specialized_disks/__init__.py
Previously, the partitioning was failing if the system also contained non-standard (e. g. multipath) disks included original LVM partitioning, as Anaconda requires the user to select all of such disks.
=> Fix disk selection behaviour for systems with specialized disks

anabot/runtime/translate.py
Anabot uses langtable to get the best guess for language id based on the language/locale selection on the Welcome screen. However, for Chinese, langtable returns *zh_XXXX_YY*, which technically might be correct, but the available translations for Anaconda are *zh_YY*.
No matter if this is a bug in the translation identifiers or not, we need to have this working, so that we can test even installations in Chinese and this workaround can be reverted in the future if there's a proper fix implemented.
To give a broader background - Anaconda gets the list of available translations based on the present localization files and their content (which, in case of Chinese, results in e. g. *zh_CN.UTF-8* as logged in anaconda.log, whereas langtable returns *zh_Hans_CN* for *简体中文 (中国)*(Simplified Chinese …
=> [RTT-4707] Workaround for proper lang ids for Chinese

anabot/runtime/installation/hub/oscap_addon/__init__.py
There was a dummy translation function, which was historically put in place as most of the OSCAP addon strings used to be untranslated and this caused problems. Now it has to be fixed for the translations to work properly, including adding underscores for the addon spoke selector.
=> [RTT-4712] Use proper translations for OSCAP addon

anabot/runtime/installation/hub/connect_to_redhat/__init__.py
Apparently 5 s may not be enough, let's try 20.
=> Increase timeout for registration to CDN 

.github/workflows/pr_checks.yaml
This is needed, because centos_stream8 job fails due to not having the config-manager installed.
=> Fix centos_stream8 job, add command to install config-manager

anabot/runtime/installation/configuration/root_password.py
Add support for the "allow root ssh login with password" checkbox, it will be used in a new TC that checks if the system can be accessed through ssh with password as root after this checkbox has been checked.
=> Add support for the "allow root ssh login with password" checkbox

.gitmodules
The repository was moved
from https://github.com/pholica/pngs2apng.git
to https://github.com/rhinstaller/pngs2apng.git
=> Update pngs2apng submodule URL

anabot/runtime/installation/hub/partitioning/advanced/details.py
If a recipe used the following setup, a bunch of unhandled exceptions (typically `anabot.runtime.errors.TimeoutError`) popped up:
```xml
<ez:installation>
...
<ez:hub>
...
<partitioning>
...
<advanced>
...
<details>
<device_type select="btrfs" policy="should_fail" />
<device_type select="lvm" />
<filesystem select="btrfs" policy="should_fail" />
<filesystem select="xfs" />
</details>
...
```
All the exceptions are now handled properly. Exceptions were caused by a device type (e.g. 'btrfs') that is recognized, but was not found in the appropriate dropdown menu.
=> Fix errors during device type and fs handling and checking

anabot/conditions.py, anabot/runtime/installation/welcome/beta_dialog.py
The terminating dots on the Beta dialog buttons have been removed in RHEL-9.3 and Fedora 39.
Beaker jobs with the changes:
J:8012823 - RHEL-9.3.0-20230622.0 with old anaconda
J:8012821 - RHEL-9.3.0-20230623.45 with new anaconda (with the dots removed)
J:8012826 - RHEL-8.9.0-20230627.22 no string change in RHEL-8
=> [RTT-5378] Update button labels on the Beta dialog

anabot/launcher.py, anabot/preprocessor/sub.py, doc/external_variables.rst, doc/index.rst, examples/sub.xml, examples/variable_substitution.xml, modules/beaker/__init__.py
External variables can be defined either on kernel command line or via Beaker task parameters. Documentation for the new functionality is included.
=> Add support for external variables

anabot/runtime/installation/hub/installation_source/additional_repo.py
Originally the handler returned Pass no matter if any repository names matched the required name, plus there was a mismatched exception handling.
=> Fix handling of additional repo selection

anabot/runtime/installation/hub/partitioning/advanced/__init__.py, anabot/runtime/installation/hub/partitioning/advanced/common.py, anabot/runtime/installation/hub/partitioning/advanced/details.py, doc/recipe_elements/advanced_partitioning.rst
There's a new element for LUKS devices unlocking (`/installation/hub/partitioning/advanced/details/luks_unlock`). I used the disk rescan functionality as part of testing and found out there are missing/malfunctioning handlers for it, so I decided to also fix them. Test jobs will be linked in RTT-5231.
=> Add support for LUKS device unlock

.gitignore, anabot/runtime/installation/hub/software_selection.py, doc/recipe_elements/software_selection.rst
This new feature allows users to choose the kernel option on aarch64. It is needed for automatic tests.
=> Support for choosing different kernels on aarch64

anabot/runtime/installation/welcome/beta_dialog.py
Anabot was failing to get through the Beta Dialog in non-English locales due to the dialog's name being localized in Anaconda. I added the translation of this name to fix the issue.
=> Fix the Anabot's Beta Dialog Problem

anabot/runtime/installation/configuration/create_user/__init__.py
When testing anabot recipe `no-root-password-no-admin-user-RHEL-10.xml`, I faced some troubles, as the test kept failing on is_admin element on RHEL-10. I investigated what happened (new checkbox annotation) and fixed the issue.
=> Add support for is_admin in RHEL 10

anabot/runtime/installation/welcome/beta_dialog.py
A regression caused by https://github.com/rhinstaller/anabot/commit/880cd0589bd1db3c5baabae1bf45afdff6abc35b
=> Beta Dialog's name is not translated on RHEL-8

anabot/runtime/installation/hub/partitioning/advanced/details.py
The previous fix of the 'page tab' disappearing in partitioning details (commit 94830798) was incomplete and when the situation to be sanitized by it happened, it couldn't actually get the visible (active) page tab node.
=> Fix base handler for advanced partitioning details

anabot/runtime/installation/hub/datetime/__init__.py
Links to testing jobs on RHEL-9 and 10 will be added to RTT-5621.
=> [RTT-5621] Support for Date & Time spoke in RHEL-10

.github/workflows/pr_checks.yaml, tests/run_suite.sh
Remove runs on CentOS7 and CS8 from the PR workflow and enable CS9. It should hopefully work fine on CS9, as I briefly tested locally by running the testing script in a CS9 container.
=> PR checks workflow update

anabot/runtime/installation/hub/partitioning/advanced/common.py
The original approch shouldn't actually break anything, but pylint was unhappy about it for a reason:
`anabot/runtime/installation/hub/partitioning/advanced/common.py:46:12: E4702: Iterated dict 'LEVELS' is being modified inside for loop body, iterate through a copy of it instead. (modified-iterating-dict)`
This pylint error was actually discovered as part of work on PR #53; this PR (#52) should likely be merged after 53, so that all of the checks pass.
=> Fix loop over dict in raid_name()

etc/systemd/system/anabot.service
I didn't realize gnome-kiosk is actually used even with Xorg, so the sleep workaround wouldn't actually apply at all. Grepping for Xorg instead should be bulletproof.
=> Fix sleep workaround with Xorg

.github/workflows/pr_checks.yaml, .github/workflows/push_deploy.yaml
- Add missing dependencies (even though they only relate to `lanabot/runtime/installation/hub/keyboard/layouts.py`, it seems better to add them instead of ignore the import errors in pylint)
- Ensure no containers using the base image are left before removing the image. This should address the current failures of the deployment phase in PR workflow, even though I have no idea how there could still be some leftover containers that are actually using the image.
=> PR workflow fixes

etc/systemd/system/anabot.service
Fix the return code of ExecStartPre, otherwise the anabot service exits:
```
sh[3851]: which: no Xorg in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
systemd[1]: anabot.service: Control process exited, code=exited, status=1/FAILURE
systemd[1]: anabot.service: Failed with result 'exit-code'.
systemd[1]: Failed to start anabot.service - Anabot.
```
=> Do not exit anabot on Wayland due to no Xorg

anabot/runtime/installation/configuration/__init__.py
Tested in a VM using a modified boot.iso and a slightly modified code making a HTTP request to a server on the host just before the reboot to record that the exception occurred and Anabot reboot was successful. Unfortunately my attempts to create a meaningful Beaker test job doing reinstallations in a loop weren't successful and I didn't want to spend more time trying to find some other way - and I think the code changes are pretty straightforward :-).
=> Reboot traceback workaround

anabot-debug.sh, etc/systemd/system/anabot-debug.service, etc/systemd/system/anaconda-direct.service.wants/anabot-debug.service, etc/systemd/system/anaconda.service.wants/anabot-debug.service, modules/anaconda_logfiles/__init__.py, modules/beaker/__init__.py
to hopefully get some useful data related to various D-Bus exceptions and potentially some other issues happening without and obvious reason.
Originally I thought about ensuring that the D-Bus traffic capture and core dump info logs will get uploaded even after a traceback in the same way as Anabot traceback logs/dumps are, but that would require even additional changes in teres. So I'd propose to only do it if we see that it's needed for real.
=> [RTT-6303] Gather D-Bus traffic and core dumps

profiles/default/hooks/99-restorecon-post.hook
so that we can make sure that anything run in post hooks doesn't break the file contexts and result in unexpected AVC denials.
=> Add post hook to run restorecon in installed system

anabot/runtime/functions.py
This fixes the issues with combo boxes. The problem is that dogtail is not able to create a mouse click with a button > 3 (4/5 are used for scrolling by mouse), but this can be overcome by generating keypresses (hopefully without undesired side effects, worked OK when I tested it). I also found out that there's an unexpected offset in the reported/actual y-coordinate positions of the menu items that needs to be accounted for (looks like a bug).
=> [RTT-6193] Fix combo_scroll on RHEL-10

modules/anaconda_logfiles/__init__.py
It was removed by mistake in dd451f67831e266d138fd267f873ed12e2faba68.
=> Upload dbus.pcap as a logfile
